### ISSUE TITLE
Negative prisudviklinger - hvad betyder det for rapportvisninger?

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#100]
I visse tilfælde skal vi kunne arbejde med negative prisudviklinger for nogle typer af omkostninger. Vi skal analysere hvad der sker med fx rapportvisninger.

**Comment by elcycefil** [comment]
Analyse viser, at i helt særlige tilfælde (ekstremt høj negativ prisudvikling kombineret med meget høje indtægter fra salg af el fra solceller) vil nutidsværdien for forsyning blive negativ. Konklusion og tabeller viser de rigtige tal, men graferne kan ikke håndtere negative værdier (vises som nul). Det rettes, når der tilføjes nye selvstændige kontoplaner for indtægter.
[Analyse af negative prisudviklinger.docx](https://github.com/Difference/LCCbygBase/files/1254610/Analyse.af.negative.prisudviklinger.docx)

**Comment by Difference** [comment]
Denne hører til andetsteds, da der ikke er tale om et issue

**Comment by Difference** [comment]
Genåbnet, da der ER tale om et issue

**Comment by Difference** [comment]
Grafer viser allerede negativer udgifter (indtægter) 
![image](https://user-images.githubusercontent.com/142553/29760809-1a151aa8-8bc6-11e7-9427-d8f9a041e302.png)
![image](https://user-images.githubusercontent.com/142553/29760869-850281e8-8bc6-11e7-998f-65eb68436015.png)
