### ISSUE TITLE
Tilføje nye prisudviklinger for energi

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#101]

**Comment by Difference** [comment]
De nye navne, enheder samt enhedspriser mangler.
Evt. nye prisudviklinger mangler.

**Comment by elcycefil** [comment]
Enhedspriser står under issue 86 og prisstigningstakter (både realt og nominelt) ligger i notat på Trello (nu også vedlagt her).
[Energi_prisstigninger.docx](https://github.com/Difference/LCCbygBase/files/1256571/Energi_prisstigninger.docx)

**Comment by elcycefil** [comment]
#86

**Comment by Difference** [comment]
Antagelser i alle projektskabeloner, på alle sprog ændres.
