### ISSUE TITLE
Undo/redo af areal under "Inddatering" virker ikke i ver. 2.2.19 

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#106]
Undo/redo-funktionen fungerer ikke for indtastning af "Bruttoareal" under "Inddatering" i udviklerversion 2.2.19.

**Comment by Difference** [comment]
Implementeret i version 2.2.20. 
Implementeringen foranledigede en omlægning af inddateringen i bruttoarealsfeltet, således at det nu er mere responsivt og automatisk vælger hele teksten, når feltet vælges. Ligeledes kan redigering afsluttes med [Enter]
