### ISSUE TITLE
Enhedsangivelser skal oversættes i den engelske projektfil.

### ISSUE THREAD

**Issue by Difference** [Difference/LCCbygBase#107]
bl.a. "stk" men muligvis også andre.

**Comment by elcycefil** [comment]
Følgende begreber skal oversættes til engelsk:
Løbende meter lbm oversættes til "running metre", bemærk ikke "meter"
Antal stk oversættes til "units"
Vægt ton til "t" eller "tonne"
Rumfang af brænde rummeter rm oversættes til "stacked cubic meter" eller hvis det er for langt til "stacked m3"
