### ISSUE TITLE
Warning: 'LCCByg 2.2.24 er holdt op med at fungere' when a new row is added.

### ISSUE THREAD

**Issue by TabtIrummet** [Difference/LCCbygBase#110]
Only on the 'For-og hovedprojekt' and 'DGNB Kontrobyggeri' templates, in the renhold field of kontoplaner sheet, when you try to add a new row (above or under the existed) on the second level, the program crashes and is forced to shut down. 
(This is occurred maybe because this renhold sheet of those templates is locked.)

**Comment by Difference** [comment]
Confirmed.
This happens on Subgroups (second level) . It's  linked to the new undo  feature, fixed in next version.
