### ISSUE TITLE
Changes in a new row are not always saved

### ISSUE THREAD

**Issue by TabtIrummet** [Difference/LCCbygBase#112]
When you create a new row and you rename it, the name is not saved unless you make further changes in the specific sheet or press enter before you move to another sheet.

**Comment by Difference** [comment]
Hard to reproduce, can you give step by step instructions? 
1st level is called Maingroup  / Hovedgruppe
2nd level is called Subgroup  / undergruppe
3rd level is called Row / Række

**Comment by TabtIrummet** [comment]
In any of the Maingroup, Subgroup or Row, when you add a new one, you have to change the name as it is created as 'unavngiven'. When you change the name you have to press and then to add the rest information otherrwise if you just go to another tab, when you go back the name is again 'unavngiven'.
Example:
Add a new row in the ‘fosyning’ field (anywhere). Change the name (without press enter), add the unit and the unit price and then move to ‘renhold’ tab. Then, go back to the ‘forsyning’. The name of the new row is not saved.

**Comment by Difference** [comment]
Reproduced! , - will fix.

**Comment by Difference** [comment]
Fixed in next version.
