### ISSUE TITLE
Engelsk version: Ikke alt oversættes

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#119]
Kommentar fra bruger: Når jeg vælger engelsk, er det ikke alt som oversættes til engelsk hvilket jeg ville forvente. Men det er muligvis heller ikke meningen?

**Comment by Difference** [comment]
Det er ikke muligt at rette dette uden nærmere angivelse af hvor der evt. mangler oversættelse. Dialogboksen "Ok" "Annuler" optræder pt. altid i det sprog der er valgt i Windows, er det denne dialog der tænkes på?

**Comment by Difference** [comment]
Da der er tale om projektfiler, som fremstår i det sprog de er forfattet i, lukkes denne.
