### ISSUE TITLE
English template: Unit mangler

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#120]
Template i English mangler enhed/unit i dropdown-menuen under fanebladet Data entry i kontoplanen Site and structures for Substructure/foundations/line foundations.

**Comment by Difference** [comment]
"rm" indsat som enhed. Enhedsangivelsen "Running metre" er samtidigt rettet til forkortelsen "rm" overalt hvor det forekommer i den engelske projektfil "Main Project".
