### ISSUE TITLE
'Fortryd' i Beskrivelse kun ved forudgående klik i Beskrivelse

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#121]
Fejl i funktionen 'Fortryd' opstår ved følgende fremgangsmåde:
- Åbn For- og hovedprojekt
- ret data i Projektbeskrivelse/Beskrivelse
- ret navn på første række i Kontoplaner/Grund, rådgivning og bygherre/Byggegrund
- ret mængde i Inddatering/Grund, rådgivning og bygherre/Byggegrund/Geo- og miljøtekniske undersøgelser

Anvend nu funktionen 'Fortryd':
- mængden rettes tilbage - ok
- navn rettes tilbage - ok
- data i Beskrivelse - kan ikke i første omgang rettes. Hvis man derimod først stiller sig i selve tekstfeltet for Beskrivelse og dernæst klikker videre på Handlinger/Fortryd, så virker det.

**Comment by Difference** [comment]
Projektinformation er ikke omfattet af det egenkodede Undo/Redo system. Her benyttes udelukkende WPFs indbyggede fortryd funktion. Det kan undersøges om det kan omlægges til de nye interne system, men det vil formodentligt være tidskrævende.
