### ISSUE TITLE
Der kan ikke arbejdes i applikationen, når online hjælp er åben

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#123]
Når online hjælpefunktionen er aktiv, så kan der ikke (i hvert fald i Chrome) skiftes mellem de to forskellige skærmbilleder for henholdsvis online hjælp og applikation. Man kan altså ikke arbejde i applikationen samtidig med at hjælpefunktionen er åben.

**Comment by Difference** [comment]
Fejlen kan ikke reproduceres. Der er fokus på om den i fremtiden kan genfindes.
