### ISSUE TITLE
Eksportnavne oversættes til engelsk

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#124]
Under Handlinger\Export findes to danske navne, som skal oversættes til engelsk:
- Regneark med resultater (-> Spreadsheet with results)
- Regneark med nøgletal (-> Spreadsheet with key figures)

**Comment by Difference** [comment]
Transformationslisten gendannes nu ved hver projektindlæsning, for at fremtvinge valg af projektsprog i underlisten.
