### ISSUE TITLE
Kalkulationsrente ændres til 5,0 % 

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#125]
Kalkulationsrenten skal ændres fra 5,5 % til 5,0 % i alle skabeloner undtagen DGNB (hvor den allerede er rettet). Renten skal rettes for alle tre perioder.

**Comment by Difference** [comment]
Kalkulationsrenten ændres altså således:

Prisudviklingsgruppen "Nominel rente og løbende priser":
År 1 = 5.0%
År 36 = 5.0%
År 71 = 5.0%

Prisudviklingsgruppen "Real rente og faste priser":
År 1 = 4.0% (uændret)
År 36 = 3.0% (uændret)
År 71 = 2.0% (uændret)

**Comment by elcycefil** [comment]
Det er de korrekte værdier.
