### ISSUE TITLE
Rapporttitel vises først i Menulinje, når der klikkes videre til et andet faneblad

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#127]
I den tidligere version af LCCbyg 2.1.9 blev menulinjen opdateret samtidig med, at brugeren skrev navnet ind i titellinjen på Projektinformation/Beskrivelse. I version 2.2.26 vises navnet først i menulinjen, når brugeren er hoppet videre til et andet faneblad. Rettes ved næste versionsudgivelse.

**Comment by Difference** [comment]
fixed ver 2.2.27
