### ISSUE TITLE
Ændre rækkefølge på alternativer

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#128]
Rækkefølgen af alternativer følger rækkefølgen i oprettelse. Det vil være nyttigt at kunne ændre rækkefølgen, så alternativerne kan placeres i en vilkårlig valgt rækkefølge, ligesom det er muligt at ændre rækkefølgen på kolonner under Inddatering.

**Comment by Difference** [comment]
Se issue #40
