### ISSUE TITLE
Under Konklusion: Navn ændres fra "Nutidsværdi" til "Sum nutidsværdi" i tabellen

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#136]
Nogle brugere er usikre på om "Nutidsværdi" er lig med summen af værdierne, som står ovenfor.

**Comment by Difference** [comment]
Engelsk oversættelse mangler

**Comment by elcycefil** [comment]
Engelsk: Sum net present value
Bemærk, at "Present value" og "Present value per m2" skal ændres til "Net present value" og "Net present value per m2".
