### ISSUE TITLE
Genvejstast Ctrl-F4 fungerer ikke korrekt

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#150]
I version 2.2.31 (og formodentlig tidligere versioner) fungerer genvejstasten Ctrl-F4 ikke korrekt, når man har låst kontoplanen Forsyning op og har kursoren stående i dropdown-menuen til valg af forskellige prisudviklinger.

**Comment by Difference** [comment]
Løst i version 2.2.41
