### ISSUE TITLE
Projektinformation: Mulighed for både logo og billede(r) af byggesag

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#167]
Der bør etableres mulighed for at indsætte både et firmalogo (som fx DGNB) og et eller endda flere billeder af byggesagen. Det vil især være relevant med billeder af byggesag i forhold til Rapportafsnit, hvor rapporten således kan få et visuelt løft og samtidig stå alene.

**Comment by Difference** [comment]
LCCbyg har indtil dato bestræbt sig på at holde binær data til et minimum, ved at begrænse det til logo. Hvis denne beslutning skal genovervejses, bør det vejses nøje imod ulemper og konsekvenser.
