### ISSUE TITLE
Sammenligningsfunktion opdateres ikke automatisk

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#173]
Version 2.2.47, DGNB-skabelon: Sammenligningsfunktionen fungerer kun, hvis brugeren vælger at sammenligne med et andet alternativ og så går tilbage til det første alternativ igen.

**Comment by Difference** [comment]
Problemet kan ikke umiddelbart reproduceres, er det muligt at vise, step by step hvordan det fremkommer?

**Comment by elcycefil** [comment]
Fejlen kan ikke reproduceres på samme måde i Forsyning. Til gengæld vises rød understregning slet ikke som markering af forskelle. 

Step-by-step reproduktion:
- åbne DGNB-hospitalsskabelon med eksempeldata
- Inddatering/Forsyning - kig på alternativ 2: Conformity check
- Varme/fjernvarme er her som standard ændret i eksemplet til 125.000 kWh sammenlignet med 75.000 kWh i Auditor-alternativ. Forskel vises ved at køre cursor henover inddateret værdi, men der er ingen rød understregning.
- Vælg Vis forskelle fra Certificering (samme værdier, så ingen forskelle).
- Vælg Vis forskelle fra Auditorversion - der er fortsat ingen markering med rød understregning.
- Ret værdi for varme/fjernvarme i alternativ Conformity check fx til 100.000 kWh - stadig ingen markering med rød understregning.

Prøv derimod med Renhold:
- åbne DGNB-hospitalsskabelon med eksempeldata
- Kontoplaner/Renhold: Tilføj ny række og sæt enhedspris til 3 kr.
- Inddatering/Renhold - kig på alternativ 2: Conformity og tilføj værdi fx 200 m2. Der vises ingen forskel med rød markering i forhold til Auditorversion (selvom værdien her er 0).
- Vælg i stedet Vis forskel i forhold til Certificering og nu fremkommer den røde markering.
- Vælg dernæst Vis forskel i forhold til Auditorversion, og nu fremkommer den røde markering også for dette alternativ, som det skal.

**Comment by Difference** [comment]
Issue del 1 (mængde i forsyning) løst. Mængde feltet i forsyning har aldrig haft sammenlignings funktionen slået til, så fejlen findes tilsyneladende i alle LCCbyg versioner indtil nu.

**Comment by Difference** [comment]
Issue del 2 løst, tilføjede rækker får nu sat deres sammenligningsversion ved oprettelse.
