### ISSUE TITLE
Fjerne tomme mellemrum og unødige linjeskift

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#175]
Version 2.2.48: Der optræder tomme mellemrum og unødige linjeskift både i start og slutningen af tekstfelterne, som skal fjernes i:
- Projektinformation/Beskrivelse
- Konklusion/Vælg det foretrukne osv.

**Comment by Difference** [comment]
Mellemrum fundet og fjernet i DGNB hospitalsskabelon.
