### ISSUE TITLE
Ctrl-z får programmet til at gå ned

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#176]
Version 2.2.48: Fortryd-funktionen kan få programmet til at holde op med at fungere, hvis man gør følgende:
- Åbne DNGB hospitalsskabelon med eksempeldata
- Kontoplaner/Forsyning: Tilføj ny række (Unavngiven række), tilføje enhed kWh og tilføje enhedspris på 0,25
- Inddatering: Tilføj mængde fx 100.000 kWh.
- Fortryd (ctrl-z) i Inddatering
- Gå til Kontoplaner: Fortryd 3 gange (først forsvinder enhedspris og dernæst enhed, som de skal). 

Tredje gang der trykkes ctrl-z får programmet til at gå ned.

**Comment by Difference** [comment]
Identificeret som: Fortryd efter tilføjelse af ny række for brogrammet til at gå ned. Rettet i version 2.2.49
