### ISSUE TITLE
Inddatering: Fortryd-funktion for kolonnen Levetid

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#179]
Version 2.2.50, **DGNB hospitals skabelon**, Inddatering/Terræn og bygning: Hvis levetiden ændres i dropdown-menuen fx ved at vælge 20 år i stedet for 80 år for Terrændæk, fugt- og varmeisolering ændres nutidsværdien i det blå felt, som den skal.
Hvis brugeren dernæst bruger Fortryd, ændres nutidsværdien tilbage til den oprindeligt beregnede nutidsværdi, men levetiden i dropdown-menuen står stadig med den ændrede værdi.

**Comment by Difference** [comment]
Der implementeres et batch system til fortryd/gendan funktionen, idet den nuværende implementering ikke tager højde for to værdier der skiftes samtidig (gruppenavn og levetid). 
Desuden: Opdateringsnotifikation sammenbindes med View.
