### ISSUE TITLE
Fortryd-funktion er ikke aktiv for Bruttoareal og Beskrivelse for Alternativer

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#180]
Version 2.2.50: Fortryd-funktionen er ikke aktiv for værdier inddateret i Bruttoareal og Beskrivelse for hvert alternativ. Det overvejes nærmere ved næste større revision af værktøjet om der skal ændres på dette.

**Comment by Difference** [comment]
Kan ikke reproduceres, er det muligt at få step by step?

**Comment by elcycefil** [comment]
Step-by-step:
- Ret bruttoareal og beskrivelse i et alternativ fx Auditorversion under kontoplan "Terræn og bygning"
- Fortryd inddatering - virker
- Gå nu til en anden kontoplan fx Forsyning - Fortryd virker ikke her (og det skal den muligvis heller ikke)
- Gå nu tilbage til den kontoplan, hvor rettelsen blev lavet. Nu virker Fortryd heller ikke her.

**Comment by Difference** [comment]
muligvis Duplicate of #182 ?
