### ISSUE TITLE
Varianter (2/2) fjernes ikke ved sletning af rækker under Kontoplaner

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#183]
Version 2.2.51: Step by step:
- Åbn Standardskabelon Disposition
- Kontoplaner: Tilføj række under Grund mv.
- Inddatering: Tilføj værdi
- Inddatering: Tilføj variant dvs. Unavngiven række - (2/2) og tilføj værdi
- Gå tilbage til Kontoplan og slet nyoprettet Unavngiven række
- Gå tilbage til Inddatering: Unavngiven række - (2/2) er der stadig
- Bemærk dog, at værdien ikke optræder i selve beregningen (det blå felt).

Prøv engang til:
- Kontoplaner: Tilføj ny Unavngiven række under Grund mv.
- Gå tilbage til Inddatering: Nu optræder både den nyoprettede Unavngiven række og den "gamle" Unavngiven række - (2/2) 
- Hvis man igen tilføjer en ny variant under Inddatering, vil der nu optræde to rækker med samme navn Unavngiven række - (2/2)

**Comment by elcycefil** [comment]
Iøvrigt kan der tilføjes endnu en variant af den slettede række og inddateres værdier. Disse indgår ikke i beregningen, men optræder alligevel i brugerinterfacet.

**Comment by Difference** [comment]
Sletning tog ikke højde for det nye variant system, fixet i version 2.2.52
