### ISSUE TITLE
Danish words on the English template

### ISSUE THREAD

**Issue by TabtIrummet** [Difference/LCCbygBase#218]
There are some Danish words in the English template that it could be nice to be translated (if this is possible). For example in Data Entry tab: there is the 'Tomme rækker' in Danish; in the report tab: all the report sections on the right side are in Danish; In the report tab: the report window is written as Rapport in the upper side.

**Comment by Difference** [comment]
<reports>
    <report name="Rapport">
      <reportsection type="image" locked="True">
        <image name="Billede" description="Et billede eller et logo der kan indsættes i rapporten" type="logo" />
      </reportsection>
      <reportsection name="Overskrift og tekst" label="LCCbyg lifecycle costing" description="Afsnit med stor overskrift og tekst" type="title">
        <inputarea />
      </reportsection>
      <reportsection name="Client">
        <input label="Client's file number" />
        <input label="Contact person/Project manager" />
        <input label="Company" />
        <input label="Street and number" />
        <input label="Zip code" />
        <input label="City" />
        <input label="E-mail" />
        <input label="Mobile" />
        <input label="Telephone" />
      </reportsection>
      <reportsection name="Consultant 1">
        <input label="Consultant's file number" />
        <input label="Role" />
        <input label="Contact person/Project manager" />
        <input label="Initials" />
        <input label="Company" />
        <input label="Street and number" />
        <input label="Zip code" />
        <input label="City" />
        <input label="E-mail" />
        <input label="Mobile" />
        <input label="Telephone" />
      </reportsection>
    </report>
    <report name="Projektinformaton">
      <reportsection name="Stamoplysninger" type="table">
        <input label="Journaliseringsnummer" />
        <input label="Kontaktperson/Projektleder" />
        <input label="Firmanavn" />
        <input label="Gade og husnummer" />
        <input label="Postnummer" />
        <input label="By" />
        <input label="E-mail" />
        <input label="Mobil" />
        <input label="Telefon" />
      </reportsection>
    </report>
  </reports>
  <reportsections>
    <reportsection name="Banner" locked="True">
      <image name="Banner" description="Et billede der stækker sig helt til kant af pdf filen"  type="banner" />
    </reportsection>
    <reportsection name="Logo" locked="True">
      <image description="Et mindre billede der placeres i ventre side" type="logo" />
    </reportsection>
    <reportsection name="Illustration" locked="True">
      <image name="Illustration" description="En illustration" />
    </reportsection>
    <reportsection name="Overskrift og tekst" description="Afsnit med stor overskrift og tekst" type="title">
      <inputarea />
    </reportsection>
    <reportsection name="Stamoplysninger" type="table">
      <input label="Journaliseringsnummer" />
      <input label="Kontaktperson/Projektleder" />
      <input label="Firmanavn" />
      <input label="Gade og husnummer" />
      <input label="Postnummer" />
      <input label="By" />
      <input label="E-mail" />
      <input label="Mobil" />
      <input label="Telefon" />
    </reportsection>
    <reportsection name="Tekstfelt" type="textarea" locked="True">
      <inputarea />
    </reportsection>
    <reportsection name="Alternativer" type="table" locked="True">
      <table name="versiondetails" />
    </reportsection>
    <reportsection name="Nutidsværdi" description="Tabel med alternativernes nutidsværdier" type="table" locked="True">
      <table name="netpresentvalues" />
    </reportsection>
    <reportsection name="Gruppeomkostninger" locked="True">
      <table name="costsbygroup" />
    </reportsection>
    <reportsection name="Klassifikations hovedgrupper" locked="True">
      <table name="costsbycode" />
    </reportsection>

    <reportsection name="Omkostninger i Kategorier" type="table" locked="True">
      <table name="costsbysecondary" />
    </reportsection>
    <reportsection name="Hovedomkostningsgrupper" type="stacked" locked="True">
      <charts name="maincostgroups" label="Hovedomkostningsgrupper" />
    </reportsection>
    <reportsection name="Hovedomkostningsgrupper" type="table" locked="True">
      <table name="maincostgroups" />
    </reportsection>
    <reportsection name="Opsummerede nutidsværdier" type="lines" locked="True">
      <charts name="summednetpresentvalues" />
    </reportsection>
    <reportsection name="Forsyning" type="lines" locked="True">
      <charts name="supply" label="Forsyning" />
    </reportsection>
    <reportsection name="Omkostningsgrupper" type="stacked" locked="True">
      <charts name="costgroups" label="Omkostningsgrupper" />
    </reportsection>
    <reportsection name="Årlig tilbagediskonterede omkostninger" type="stacked" locked="True">
      <charts name="npvversionstacked" />
    </reportsection>
    <reportsection name="Begreber" type="textarea" locked="True">
      <inputarea label="Tekstblok">
          Nutidsværdien defineres som summen af de tilbagediskonterede fremtidige pengestrømme. Nutidsværdien er et udtryk for hvor mange penge, der skal sættes til side i dag, for at kunne afholde alle fremtidige omkostninger i beregningsperioden.

          Årsomkostningen defineres som en annuitet af nutidsværdien. Årsomkostningen udtrykker hvor mange penge, der gennemsnitligt skal afsættes hvert år i beregningsperioden.
        </inputarea>
    </reportsection>
  </reportsections>

**Comment by Difference** [comment]
Those are the sections that are missing translation. Some Copy paste is possible.

**Comment by elcycefil** [comment]
Omkostninger i Kategorier = Cost by categories
Hovedomkostningsgrupper = Main cost groups
Opsummerede nutidsværdier = Summarised net present values
Forsyning = Supply
Omkostningsgrupper = Cost groups
Årlig tilbagediskonterede omkostninger = Discounted cash flows per year
Begreber = Definitions
The net present value is defined as the sum of the discounted future cash flows. The net present value is an expression of how much money should be set aside today to pay all future costs in the calculation period.
Annuity cost (in Danish: Årsomkostning) is defined as the annuity of the net present value. It expresses how much money should be allocated every year on average during the calculation period.

**Comment by Difference** [comment]
![image](https://user-images.githubusercontent.com/142553/65748364-0fa37480-e104-11e9-8509-d5a2d8225cb6.png)

Stamoplysninger = Participant info?

**Comment by elcycefil** [comment]
Iate, Ordbogen og Google Translate giver tre forskellige svar, men det mest korrekte synes at være "Master data".

**Comment by elcycefil** [comment]
Textarea skal være Text area eller bedre "Supplementary information"

**Comment by Difference** [comment]
"Stamoplysninger", dækker over "Byggesag" "Bygherre" "Rådgiver" og muligvis andre, da der frit kan angives rubrikoverskrift , Master data er vist ikke helt generisk nok.

**Comment by elcycefil** [comment]
Master data er det mest korrekte og dækkende udtryk.

**Comment by Difference** [comment]
Master data er nok for stærkt et begreb, jvf. f,eks https://en.wikipedia.org/wiki/Master_data

**Comment by elcycefil** [comment]
Den mest autoritative oversættelseskilde er EU's IATE-database, som angiver "master data".

**Comment by Difference** [comment]
closed as "Master data"
