### ISSUE TITLE
Interest rate and Price development field in English template

### ISSUE THREAD

**Issue by TabtIrummet** [Difference/LCCbygBase#222]
In all standard templates, there are three options for rate and price development (namely Nominal interest and current prices, public buildings, and zero development). The English template, however, doesn't have those three options but it has two options similar to the DGNB certification template (namely Nominal interest rates and current prices, and real discount rate and fixed prices) - I am not sure if this should be changed or there is a reason for that.
Moreover, 'Real discount rate and fixed prices' is set by default in the English template, while in all others the 'Nominal interest and current prices' is the default setting.

**Comment by elcycefil** [comment]
The three standard options should also be available in the English template. 

A fourth option for Real discount rate and fixed prices should be added to all templates.

**Comment by Difference** [comment]
This issue is for the english template, if more sets are to be added to other templates, please state it in a different issue. (i'm not sure they should be in other than "Nyt Stabdardproject" )

**Comment by Difference** [comment]
fixed in english template
