### ISSUE TITLE
Fjerde forudsætningssæt tilføjes

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#229]
Det skal være muligt at lave beregninger vha. samme realrente over hele beregningsperioden og faste priser. Der tilføjes et nyt fjerde forudsætningssæt med:
- Realrente 3 % gældende for hele beregningsperioden
- Faste priser, dvs. prisudvikling generelt på 0 % (og tilsvarende justeringer på -2 % for alle øvrige prisudviklinger).

**Comment by Difference** [comment]
Der er allerede tilføjet et sådan beregningssæt til skabelonen “Nyt standardprojekt” Er der behov for justering af dette?

Hvis dette sæt også ønskes i den engelske skabelon, skal det navngives på engelsk

**Comment by elcycefil** [comment]
Der er ikke behov for at justere beregningssæt i den danske skabelon "Nyt standardprojekt".
Beregningssættene i den engelske udgave skal hedde: 
- Public projects
- Nominal discount rate and current prices
- Real discount rate and fixed prices
- Zero discounting (and price development - hvis der er plads i titlen)

**Comment by Difference** [comment]
Implemented
