### ISSUE TITLE
Rumtype-vælger i DGNB-skabelon

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#232]
Valg af rumtype fx sengestue i DGNB-skabelonen burde rette levetid til 15 år eller 30 år, men det sker ikke.
![DGNB-rumtype](https://user-images.githubusercontent.com/18067512/65626881-7d4d8480-dfce-11e9-85de-13ec7e04ffdd.JPG)

**Comment by Difference** [comment]
"Rumtype" / BOSSINF dropdown er udelukkende en annoteringsfunktion, der tillader at der oprettes resultattabeller i disse grupper. Der er ikke tilknyttet egenskaber til annoteringen. En evt. begrænsning/læsning af egenskaber, skal løses i sin egen designprocces. Dette issue lukkesderfor. Et nyt issue kan evt. oprettes til at fange dette featureønske, men bør nok igennem en designprocess, før at formulere det optimalt.
