### ISSUE TITLE
Kan de to DGNB skabeloner sammenlægges?

### ISSUE THREAD

**Issue by Difference** [Difference/LCCbygBase#233]
Det synes unødvendigt at have 2 skabeloner, da  de bortset fra rumtyper er ens.

**Comment by elcycefil** [comment]
Ja, hvis rumtypevælgeren fungerer.

**Comment by Difference** [comment]
Rumtypevælger fungerer pt. korrekt, se #232 .

**Comment by Difference** [comment]
Vi udskyder evt, sammenlægning til en god beslutning kan træffes. På Den måde kan eksisterende dokumentation stadig benyttes.
