### ISSUE TITLE
Kan prisudviklingssæt i DGNB skabelon reduceres?

### ISSUE THREAD

**Issue by Difference** [Difference/LCCbygBase#234]
Hvis certificering kræver at man benytter et bestemt prisudviklingssæt, bør kun dette sæt være tilstede i skabelonen.

**Comment by elcycefil** [comment]
Ideelt set bør der kun være det ene relevante prisudviklingssæt tilgængeligt. Imidlertid vil i hvert fald nogle brugere gerne kunne bearbejde en DGNB-beregning med andre prisudviklingssæt og eksempelvis vise usikkerheden på beregningen. Alle prisudviklingssæt bør derfor nok i udgangspunktet være tilgængelige (det vil formodentlig også gøre det lettere at vedligeholde systemet). En endelig afklaring kan evt. afvente input fra brugertest.

**Comment by Difference** [comment]
Det er det enkleste kun at have eet udviklingssæt, som brugeren jo så kan kopiere, hvis der ønskes varianter. Bemærk at det, selvom det er muligt at bruge et udviklingssæt til følsomhedsberegning, nok ikke bør kommunikeres som en feature, idet man må forvente, at der kommer en egentlig funktionalitet til følsomhed i en fremtidig vesrion.

**Comment by Difference** [comment]
I så fald vi sættes alle 4 udviklingsæt i DGNB skabelonen.

**Comment by Difference** [comment]
Fixed
