### ISSUE TITLE
Resultatfelt ("det blå felt") glider ud af skærmen ved lang kontoplan

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#236]
Hvis Kontoplaner er åben med et dybt hierarki fx Kontoplaner/Terræn og bygning/Primære bygningsdele/Ydervægge, så glider resultatfeltet ("det blå felt") ud af bunden på skærmen. Resultatfeltet dukker naturligvis op igen, når kontoplanen foldes sammen. Det kan muligvis være irriterende for brugeren, som ikke kan se resultatet af sine beregninger uden at folde kontoplanen sammen igen. Stillingtagen afventer brugerfeedback.

**Comment by Difference** [comment]
Løst med ny tabel og splitter

![image](https://user-images.githubusercontent.com/142553/67491669-90a74a80-f675-11e9-9fc9-b902db9359bc.png)
