### ISSUE TITLE
Proofreading in English template: capital letters etc.

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#237]
In the English template, capital letters are used not only at the beginning but also in the middle of a text like "Period of Calculation". It is not applied uniformly across the template (e.g. "Gross floor area"). 
We will apply the notation that only starting letters are spelled with capital letters. 

Spelling error: "Rate and Price Develpment" should be: "Rate and price development"

**Comment by Difference** [comment]
All internal strings now follows this convention. Project template is a separate issue ( see #218 )
