### ISSUE TITLE
English template: translation of names

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#238]
The English template needs a translation of names:
Tomme rækker = Empty rows

Det samme gælder, når rækken er trukket over i Unnamed Group, hvor navnet står på dansk "Ny række". Oversættes til "New row".

Prerequisites ændres til Assumptions.

Anskaffelse = Acquisition costs
Engangsudgift = Non-recurring costs
Bygningsdel = Building component costs
Forvaltning = Management costs
Forsyning = Utility costs
Renhold = Cleaning costs
Løbende indtægt = Recurring income 
Engangsindtægt = Non-recurring income

**Comment by Difference** [comment]
Fixed. Bemærk dog at "Ny række" > Oversættes til "New row"." udgår, da disse betegnelser er taget ud, fordi de var for svære at vedligeholde. Nye rækker har således deres "basisnavn"  men kan stadig navngives som man ønsker det. efterfølgende.

**Comment by elcycefil** [comment]
Prerequisites skal ændres til Assumptions

**Comment by Difference** [comment]
fixed

**Comment by Difference** [comment]
fixed
