### ISSUE TITLE
Navnelinjen rettes

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#240]
I navnelinjen anvendes navnet LccByg. Det skal rettes til LCCbyg.

Desuden kommer der ikke længere en angivelse af skabelontype (fx Standardprojekt), ligesom navnet på projektet ikke længere optræder.

**Comment by Difference** [comment]
Fixed, closes #244 Først forekommende "Overskrift og tekst" sektion, i første rapport, bindes nu til projekttitel. Der bør findes en mere forklarende metode til inddatering af projekttitel.
