### ISSUE TITLE
Notation af fx Operationsstue er ikke tilgængelig i DGNB-skabelon

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#252]
Notation til angivelse af kortere levetid for sengestue og operationsstue er ikke tilgængelig i DGNB-skabelonen.
![image](https://user-images.githubusercontent.com/18067512/65899060-32a78000-e3b3-11e9-8572-103df3320193.png)

**Comment by Difference** [comment]
Menes der at dropdown med "Rumtype" ikke er tilgængelig? Levtid er jvf.  ##232 og #245 ikke en del af annoteringen

**Comment by Difference** [comment]
Dropdown "Rumtype" er nu tilgængelig i begge DGNB skabeloner.
