### ISSUE TITLE
Hovedomkostningsgrupper vises ikke korrekt i 

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#253]
Eksempel på standardprojekt: 
Værdierne er korrekte, men anskaffelsesomkostninger (i blåt) vises kun delvist i figuren i "Hovedomkostningsgrupper". 

![image](https://user-images.githubusercontent.com/18067512/65899277-b3667c00-e3b3-11e9-9a5a-5af5f2cda67c.png)

**Comment by Difference** [comment]
Fejlen er svær at diagnogsticere og ser ud til at komme fra grafbibliotetket. Pdf'en viser grafen korekt.

![image](https://user-images.githubusercontent.com/142553/65913912-f256fa80-e3d0-11e9-9435-2693cfcb0727.png)

**Comment by Difference** [comment]
fixed, ved at lave sektionen lidt større. Genåb dette issu, hvis fejlen viser sig igen.
