### ISSUE TITLE
Rækketype forklaring mangler i listevisning.

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#275]
Ved søgning i kontoplaner på fx Vindue får brugeren en liste over relevante rækker om vinduer. Det giver dog tre udfordringer: 
1) Hvad betyder farverne? I søge-mode er det ikke længere tydeligt, hvad de forskellige farver betyder.
2) En del navne er identiske fx "Vinduer", hvilket gør det umuligt at finde ud af, hvad rækken indeholder (med mindre brugeren trækker rækken over, kigger detaljerne igennem og evt. finder en ny række).
3) Navne kan være lange, fordi de også indeholder geometrisk placering (indervægge, ydervægge mv.), som gør det sværere at finde det rigtige vindue.

![image](https://user-images.githubusercontent.com/18067512/66030371-7dcfa900-e501-11e9-88e1-3b55a493b063.png)

**Comment by Difference** [comment]
Dette issue er 3 seperate issues, 
1) "Opgave" mangler i visning af navn, løses i #276
2) Dette issue konverteres til "Rækketype forklaring mangler i listevisning"
3) Lange navne oprettes evt som seperat issue i "Levetider"?

**Comment by Difference** [comment]
løst med rækkketype kolonne
![image](https://user-images.githubusercontent.com/142553/66037585-3b619880-e510-11e9-9b8f-cec1ca247154.png)
