### ISSUE TITLE
Opgave ( task ) importeres/eksporteres ikke til regneark

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#276]
I Kontoplaner er det ikke klart, hvad der adskiller renhold af vinduer. Der er 3 slags vinduer, men ingen yderligere identifikation af belastning kan hjælpe brugeren.

Bemærk også, at det ikke fremgår i rækkedetaljer, hvad opgaven er: Let, almindelig, krævende.

![image](https://user-images.githubusercontent.com/18067512/66031155-1c103e80-e503-11e9-9b77-ac7afddc4e3e.png)

**Comment by Difference** [comment]
"Opgave" mangler i visning af navn i både trævisning og listevisning se også #275

**Comment by Difference** [comment]
Problemet opstår fordi import/eksport ikke medtager "opgave" korrekt.

**Comment by Difference** [comment]
importer fixed
