### ISSUE TITLE
Rapporter: Nutidsværdi vises ikke for alle alternativer

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#278]
I Rapporter vises resultaterne ikke for alle alternativer.

![image](https://user-images.githubusercontent.com/18067512/66035888-4b777900-e50c-11e9-8239-88ed59fc2e05.png)

**Comment by Difference** [comment]
Upload eller email venligst projekt, eller angiv step by step for at reproiduecere dette issue.

**Comment by Difference** [comment]
fejlen kan indsnævres til at der benyttes skråstreg i navnet på disse alternativer

**Comment by Difference** [comment]
"/" konverteress nu til "-" i tabelvisninger og Pdf. 
Alternativer kan stadig navngives med skråstreg, men det vises som "-".

**Comment by Difference** [comment]
Genåbnet fordi problemet også gælder "."

**Comment by Difference** [comment]
rettet for "."
