### ISSUE TITLE
Inddatering: Enheder fremgår ikke

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#279]
Inddatering: Enheder på de anførte mængder og enhedspriser fremgår ikke. Det er især et problem i forhold til forsyningspriser, som er anført i kWh, og ikke som fx MWh.

**Comment by Difference** [comment]
Enheder implementeret. Ingen skabeloner indeholder dog pt. enheder, der jo heller ikke har været en del af interface og import/eksport op til nu.
