### ISSUE TITLE
Scrollefunktion i Rapporter "lagger"

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#281]
Der er en tendens til at scrollefunktionen i Rapporter "lagger" og stopper op undervejs, når brugeren forsøger at scrolle ved hjælp af musens rullehjul i stedet for at bruge scroll-baren i højre side.

**Comment by Difference** [comment]
Når musen holdes over en tabel i rapporten, er det det det element der modtager scroll information.  
Denne information forwardes nu til rapporten.
