### ISSUE TITLE
Negativ prisudvikling kan ikke inddateres

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#291]
Ved kopiering af fx udviklingssættet for Offentlige bygherrer kan prisudvikling for fx fjernvarme ikke ændres til -1 %.

**Comment by Difference** [comment]
Programmet begrænser pt. prisudviklinger til at være positive. Skal negative prisudviklinger være mulige?

**Comment by elcycefil** [comment]
Ja, negative prisudviklinger skal være mulige, ligesom de var i version 2.2.52, hvor gas var sat til -0,5 %.

**Comment by Difference** [comment]
Implementeret med en maximal negativ prisudvikling på -25,00
