### ISSUE TITLE
I skabeloner for Almene boliger med SfB og DFK mangler 'Realrente og faste priser' i prisudvikling

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#297]
I de to skabeloner for almene boliger, mangler der 'Realrente og faste priser' i drop-down menu for 'Rente og prisudvikling'.

**Comment by Difference** [comment]
version 3.0.04?

**Comment by HAW19** [comment]
Fejl rettet i version 3.0.04
