### ISSUE TITLE
Farver/farvekoder

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#300]
Farveblinde kan ikke skelne mellem de forskellige farver. Det kan muligvis løses ved at indsætte supplerende ikoner, der gør det nemmere for farveblinde at genkende.

**Comment by Difference** [comment]
"Træk" ikonet ændres til et rækkespecifikt ikon, således er der er mere information om rækken, uden at der går ekstra plads til det.

![image](https://user-images.githubusercontent.com/142553/66563739-c0772e00-eb5e-11e9-9a06-e237286fc70d.png)

![image](https://user-images.githubusercontent.com/142553/66563773-cd941d00-eb5e-11e9-9e18-32283ee746b1.png)

![image](https://user-images.githubusercontent.com/142553/66563817-e3a1dd80-eb5e-11e9-8f84-f700ae35e51f.png)

![image](https://user-images.githubusercontent.com/142553/66563924-1cda4d80-eb5f-11e9-8f5f-0ee2762affba.png)

**Comment by Difference** [comment]
Samme greb benyttes til rapportafsnittene, således at der ikke er mere en et ikon per afsnit:

![image](https://user-images.githubusercontent.com/142553/66564089-7cd0f400-eb5f-11e9-963b-91c67397b3ea.png)
