### ISSUE TITLE
Start, Slut og Interval (år) på gruppe niveau?

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#304]
Der kan ønskes en virkemåde, hvor en hel gruppe benytter samme Start og Slut (år) 
Der bør undersøges usecases for dette, for at se om det imødekommer behovet for at peridodificere udskiftninger.

**Comment by Difference** [comment]
Titel ændret, issues skal være specifikke.

**Comment by Difference** [comment]
Ved at tilføje Interval på gruppeniveau, kan man, når #350 er implementeret, imødekomme udskiftningsintervaller der er hyppigere end levetiden, for hele grupper, uden at levetiden "strækkes" for levetider der er kortere end intervallet.
