### ISSUE TITLE
Rente- og prisudviklingssæt - resultat ændres ikke

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#305]
Det er forvirrende, at resultaterne fremstår med samme værdi uanset hvilket rente- og prisudviklingssæt, brugeren betragter. Det overvejes, om værdierne skal ændre sig for at vise konsekvenserne ved skift af rente- og prisudviklningssæt og / eller om vejledning skal uddybe og forklare.

**Comment by Difference** [comment]
Resultatet skal ændre sig når der skiftes udviklingssæt, hvis sættet indeholder andre værdier end det anvente. Kan fejlen reproduceres step by step?

**Comment by Difference** [comment]
Kan evt. løses ved, at kun alternativer der benytter det valgte sæt vises.

**Comment by elcycefil** [comment]
Det er en observation fra sektionen "Forudsætninger".

**Comment by Difference** [comment]
Resultater er fjernet fra Forudsætninger, så de er tilbage til virkemåden i ver 2.2,x der virker mere intuitiv, indtil visningen måske kan videreudvikles. 
( Skulle være uproblemetisk, da resultatvisningen har ikke optrådt i wireframes/kravspec og er tilføjet som "nice to have" )
