### ISSUE TITLE
Hvordan vender man tilbage til forsiden fra ‘Nyt Standardprojekt’

### ISSUE THREAD

**Issue by huonulolo** [Difference/LCCbygBase#313]

**Comment by Difference** [comment]
Dette er et support spørgsmål og ikke et issue og lukkes derfor.

**Comment by Difference** [comment]
Hej huonulolo : Vi er meget glade for testere, men da dette ligner et support spøgsmål, vil vi gerne i kontakt med dig. Vil du skrive til os på lccbyg@sbi.aau.dk ? 

På forhånd tak.
