### ISSUE TITLE
Tilvalg af enheder i standardskabelon virker ikke

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#315]
I standardskabelonen kan enheder ikke tilvælges fra dropdown-menu. Overvejes om det er nødvendigt.

![image](https://user-images.githubusercontent.com/18067512/67425284-ff35cb00-f5d7-11e9-94ce-eaccf91a9019.png)

**Comment by Difference** [comment]
Kan ikke reproduceres med tomt standardprojekt eller eksempelprojekt i version 3.0.04, step by step er nødvendig.

![image](https://user-images.githubusercontent.com/142553/67460642-d0e9d700-f63b-11e9-8418-4e73fb8c23f7.png)

**Comment by elcycefil** [comment]
Issue kan ikke reproduceres. Lukkes.
