### ISSUE TITLE
i rapport af 'new standard project in English', sprog i 'Maingroups by classification' er på dansk

### ISSUE THREAD

**Issue by huonulolo** [Difference/LCCbygBase#320]

**Comment by Difference** [comment]
klassifikations hovedgrupper skal oversættes til engelsk i denne skabelon

**Comment by Difference** [comment]
Rettet i version 3.0.05 til: 

 
      <group name="Substructure" code="1" />
      <group name="Structure, primary elements" code="2" />
      <group name="Completions" code="3" />
      <group name="Applied finishes" code="4" />
      <group name="Sanitation and HVAC services" code="5" />
      <group name="Electrical services" code="6" />
