### ISSUE TITLE
'maintenance interval' i 'Data entry' er forvirrende med lifetime

### ISSUE THREAD

**Issue by huonulolo** [Difference/LCCbygBase#321]
![maintenance interval](https://user-images.githubusercontent.com/48910135/67640921-de35e880-f8fd-11e9-95d6-32071eb0510f.png)

**Comment by Difference** [comment]
Prøv at skrive lidt mere om problemet. "Interval" er et udtryk for hvor tit der vedligeholdes.

**Comment by huonulolo** [comment]
Spørgsmålet er, hvilket år forekommer hver vedligeholdelse, f.ex. hvornår ske disse 4 interval?

**Comment by Difference** [comment]
Ok, forstået - Ja, det vil være godt med en visning af rækkens "begivenheder", måske i en lille "graf/kalender" i rækkedetaljerne.

**Comment by huonulolo** [comment]
NPV kan ikke beregnes hvis vi ved ikke hvilket år det sker.

**Comment by Difference** [comment]
Hej huonulolo, har du mulighed for at dele dine kontaktoplysninger med mig, så jeg kan ringe og afklare problematikken?

**Comment by Difference** [comment]
Se iøvrigt gerne: 
![image](https://user-images.githubusercontent.com/142553/67683262-5a2d4080-f991-11e9-8f83-3c56ab251ddf.png)

![image](https://user-images.githubusercontent.com/142553/67683292-6addb680-f991-11e9-9924-d3ced0a6d493.png)

**Comment by huonulolo** [comment]
Ok, forstået. Figuren giver en god forklaring.
