### ISSUE TITLE
'Rumtype' i 'Renhold' i dansk version er mangler i engelsk version

### ISSUE THREAD

**Issue by huonulolo** [Difference/LCCbygBase#322]

**Comment by Difference** [comment]
Rumtype forekommer kun i DGNB skabeloner, kan der forklares nærmere?

**Comment by elcycefil** [comment]
Det skal overvejes, om rumtyper fremadrettet skal tilføjes til alle skabeloner. Det vil dog være en del af en større overvejelse om at indføre et egentligt rumprogram.
