### ISSUE TITLE
enhed er mangler i 'New standard project in English'

### ISSUE THREAD

**Issue by huonulolo** [Difference/LCCbygBase#323]

**Comment by Difference** [comment]
Enhedstabel tilføjet den enegelse skabelon.

  <group name="Building parts">
        <group name="m" />
        <group name="m2" />
        <group name="m3" />
        <group name="rm" />
        <group name="lbm" />
        <group name="stk" />
        <group name="kg" />
        <group name="ton" />
      </group>
      <group name="Supply">
        <group name="kWh" />
        <group name="MWh" />
        <group name="m3" />
        <group name="rm" />
        <group name="l" />
        <group name="kJ" />
        <group name="MJ" />
        <group name="ton" />
      </group>
      <group name="Other">
        <group name="kr" />
      </group>
