### ISSUE TITLE
Beregningsperioden i 'Inddatering' kan ikke ændres til en værdi, der er højere end 50. Den kan kun sættes til 50 eller mindre. 

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#329]

**Comment by Difference** [comment]
Hvilken skabelon er der tale om?

**Comment by HAW19** [comment]
Det gælder alle skabeloner, på nær skabeloner for Almene boliger med DFK og SfB

**Comment by Difference** [comment]
er beregningsperioden sat til mere end 50 år?

**Comment by Difference** [comment]
Fejl fundet, rettes i de berørte skabeloner
