### ISSUE TITLE
Terrænomkostninger

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#33]
KH: Der findes en tilrettet DNGB-skabelonen i eksempelprojektet, så alle terrænomkostninger med tilhørende levetider, vedligeholdsprocenter og genopretning er med. Det skal også ske for de øvrige skabeloner. Se eksempelprojektet for en uddybning.

**Comment by Difference** [comment]
Den tilrettede skabelon og/eller værdier savnes.

**Comment by elcycefil** [comment]
GitHub understøtter ikke xml-filer, så projektfil er fremsendt per mail.

**Comment by Difference** [comment]
https://github.com/Difference/LCCbygBase/blob/master/DGNB/DGNB-eksempelprojekt.xml

**Comment by Difference** [comment]
Her er en simpel måde at upload xml filer, omdøb dem til filtype "txt" . Nemmest gjort ved at sætte .txt efter filnavnet, således at man kan se hvad den skal omdøbes til.

[DGNB-eksempelprojekt.xml.txt](https://github.com/Difference/LCCbygBase/files/580310/DGNB-eksempelprojekt.xml.txt)

**Comment by elcycefil** [comment]
[DGNB-eksempelprojekt_ver4.xml.txt.txt](https://github.com/Difference/LCCbygBase/files/580363/DGNB-eksempelprojekt_ver4.xml.txt.txt)

**Comment by elcycefil** [comment]
Eksempelprojekt ver4 rummer de rigtige værdier. Alle enhedspriser er opgjort i kWh i stedet for ton, l, m3 og MWh efter aftale med DK-GBC.
Forklaring/notetekster til vejledning/manual vedr. energi:
-	Træpiller: Brændværdi 5 kWh/kg, virkningsgrad ca. 80 %, pris 1.600 kr/tons ekskl. moms = 0,40 kr/kWh
-	Olie: Brændværdi 10 kWh/l, virkningsgrad 85 %, pris 9,47 kr/l ekskl. moms = 1,11 kr/kWh
-	Gas: Brændværdi 11 kWh/m3, virkningsgrad 100 %, pris 7,14 kr/m3 ekskl. moms = 0,65 kr/kWh
