### ISSUE TITLE
Stavefejl i rapport

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#334]
Rapportafsnittet "Beregningsforudsætninger" rummer en stavefejl.
![image](https://user-images.githubusercontent.com/18067512/67985383-09d01000-fc29-11e9-8c22-26250a5021eb.png)

**Comment by Difference** [comment]
Kan ikke reproduceres. 
Hvilken projekttype er der tale om?

Bemærk at stavefejl ikke kan rettes bagudrettet i projekter der allerede er gemt med stavefejl, i det teksterne jo ligger i projektfilen og ikke i LCCbyg applikationen.

**Comment by Difference** [comment]
Rechecked
