### ISSUE TITLE
Stavefejl i "Rapporter": 'Projektinformaton' indeholder en stavefejl.

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#336]

**Comment by Difference** [comment]
Kan ikke reproduceres. 
Hvilken projekttype er der tale om?

Bemærk at stavefejl ikke kan rettes bagudrettet i projekter der allerede er gemt med stavefejl, i det teksterne jo ligger i projektfilen og ikke i LCCbyg applikationen.

**Comment by HAW19** [comment]
![image](https://user-images.githubusercontent.com/55234063/68107248-7e82a300-fee4-11e9-8385-4a3cb7cac84c.png)

**Comment by HAW19** [comment]
Fejlen er fundet i version 06, og gælder samtlige skabeloner.

**Comment by Difference** [comment]
Tak, fundet, (var allerede rettet i v 3.0..7 )
