### ISSUE TITLE
'DGNB typer' result er tomt i rapport 

### ISSUE THREAD

**Issue by huonulolo** [Difference/LCCbygBase#338]
I rapport for 'eksempel for kontor til DGNB-certificering', 'DGNB typer' result er tomt.

**Comment by Difference** [comment]
Der skal vælges "Type" i inddatering, før noget vises.


![image](https://user-images.githubusercontent.com/142553/68130079-0a172680-ff1b-11e9-9de8-5f0499c109f3.png)

![image](https://user-images.githubusercontent.com/142553/68130129-1c916000-ff1b-11e9-9715-0326088fd1c6.png)

**Comment by HAW19** [comment]
I version 06 kan der ikke vælges 'Type' i skabelon for 'Kontor til DGNB-certificering'

**Comment by HAW19** [comment]
![image](https://user-images.githubusercontent.com/55234063/68131559-8dd21280-ff1d-11e9-964b-0daeff96e007.png)

**Comment by HAW19** [comment]
I de to DGNB skabeloner for kontorer og hospitaler kan der vælges 'Rumtype' og ikke 'Type'

**Comment by HAW19** [comment]
![image](https://user-images.githubusercontent.com/55234063/68131811-fde09880-ff1d-11e9-87c0-15cdaeb68f5f.png)

**Comment by Difference** [comment]
Det er korrekt virkemåde, der findes pt. ikke et typebegreb for DGNB.

**Comment by Difference** [comment]
DGNB rumtyper er borttaget, idet der nu benyttes grupper til denne opdeling.
