### ISSUE TITLE
Prisudviklingssæt: Et alarmsystem, der gør brugeren opmærksom på, at der er valgt forskellige prisudviklingssæt i alternativer.

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#340]

**Comment by Difference** [comment]
Dette løses ved at comboxen med prisudviklingssæt skifter tekstfarve, alt efter om værdien er arvet fra den generelle prisudvikling i skabelonen eller ikke.

Denne visning er konsekvent i forhold til den eksisterende "arvet værdi" metodik.

Ydermere markeres skabelonens default prisudvikling med arvet værdi farve (pt. grøn) " i dropdown dialogen, således at der kan findes tilbage til udgangspunktet, idet man i comboboxen jo ikke har mulighed for at fravælge en værdi.

![image](https://user-images.githubusercontent.com/142553/68652726-5caf9e80-052a-11ea-83e2-4fb396dbb64c.png)
