### ISSUE TITLE
Nye navne til prisudviklingssæt.

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#341]

**Comment by Difference** [comment]
Husk beskrivelser jvf. #342 samt at der også skal fremstilles engelske navne og beskrivelser.

**Comment by Difference** [comment]
__
![image](https://user-images.githubusercontent.com/142553/68763784-96ab9e00-0619-11ea-96e7-b46a42d9b7ec.png)

**Comment by elcycefil** [comment]
Offentlige bygherrer ændres til: Faldende realrente 
o	Dette sæt af forudsætninger for kalkulationsrente og prisudvikling skal anvendes af offentlige bygherrer. Rentetrappen anvender faldende realrente og faste priser. De anførte rentesatser og intervaller fremgår af Finansministeriets vejledning af 12. november 2018 med titlen ”Den samfundsøkonomiske diskonteringsrente”.

Nominel rente og løbende priser ændres til: Fast nominel rente
o	Dette sæt af forudsætninger for kalkulationsrente og prisudvikling anvendes fx af DGNB til certificering. Kalkulationsrenten opgøres nominelt, og priserne opgøres som løbende priser (dvs. inklusiv inflation) over hele beregningsperioden.

Realrente og faste priser ændres til: Fast realrente
o	Dette sæt af forudsætninger anvendes af almene bygherrer. Kalkulationsrente og prisudvikling opgøres som fast realrente og faste priser (dvs. uden inflation) over hele beregningsperioden. 

Nuludvikling ændres til: Nuludvikling
o	Dette sæt af forudsætninger anvendes i situationer, hvor udvikling af både kalkulationsrente og priser ønskes at være nul. Det kan bl.a. være nyttigt ved kontrol af beregninger.

**Comment by Difference** [comment]
Engelsk version mangler

**Comment by elcycefil** [comment]
Engelske navne:
- decreasing real interest rate
- fixed nominal interest rate
- fixed real interest rate
- zero interest rate

**Comment by Difference** [comment]
Ligesom de danske, skal der tilføjes beskrivelser på de engelske udviklinger.

**Comment by elcycefil** [comment]
Rettelse til: Realrente og faste priser ændres til: Fast realrente
o Dette sæt af forudsætninger anvendes af almene bygherrer og mange andre. Kalkulationsrente og prisudvikling opgøres som fast realrente og faste priser (dvs. uden inflation) over hele beregningsperioden.

**Comment by elcycefil** [comment]
Decreasing real interest rate
- This set of assumptions for discount rate and price developments must be used by public clients. The interest rate is stated in steps for different time periods with decreasing real interest rates and fixed prices. The stated interest rates and ranges appear in the Ministry of Finance's guidance of November 12, 2018 entitled "Den samfundsøkonomiske diskonteringsrente".

Fixed nominal interest rate
- This set of assumptions for discount rate and price developments is used, for example, by DGNB for certification. The discount rate is determined nominally, and prices are stated in current prices (i.e. including inflation) over the entire calculation period.

Fixed real interest rate
- This set of assumptions is used by social housing companies and many others. Discount rate and price developments are stated as fixed real interest rate and fixed prices (i.e. without inflation) over the entire calculation period.

Zero interest rate
- This set of assumptions is used in situations where both the discount rate and price developments are to be zero. It may be useful e.g. in checking calculations.

**Comment by Difference** [comment]
Implementeret i alle skabeloner.
