### ISSUE TITLE
Tilføj byggeomkostningsindeks som prisudvikling (i "Forudsætninger").

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#344]

**Comment by elcycefil** [comment]
Overvejes nærmere på et senere tidspunkt, især i lyset af de udfordringer, som byggeomkostningsindekset indebærer. Der er ikke tale om egentlige priser, men et indeks. Desuden er det ikke et enkelt indeks, men fire forskellige, som i øvrigt er underopdelt i yderligere tre: Sum, materialer og mandtimer.
