### ISSUE TITLE
"Inddatering" - overvej nye navne til "Tomme rækker"

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#347]

**Comment by elcycefil** [comment]
Anskaffelse går igen som både navn på række og som posteringstype. Posteringstype beholdes på tværs af øvrige rækker, mens navn på række ændres.

Ved nærmere analyse er det reelt kun rækken "Grundkøbesum", som er relevant at bevare for at kunne beregne en restværdi. De øvrige omkostninger er alle af typen engangsudgifter, som ikke skal have beregnet en restværdi. Engangsudgifter omfatter en lang betalinger knyttet til grund, rådgivning og bygherrens egne omkostninger til projektudvikling.

Den tomme række "Anskaffelse" omdøbes til "Grundkøb" på dansk og "Land acquisition" på engelsk (jfr. RICS' new rules of measurement).

**Comment by elcycefil** [comment]
"Tomme rækker" omdøbes til "Blank rows" på engelsk.

**Comment by elcycefil** [comment]
Flere forskellige mulige løsninger på navne er blevet undersøgt fx aktivitet (i tråd med REBUS effekt-kæde-model, men kolliderer med DFK's definition af Aktiviteter), posteringer (anvendes til andre formål), konto / kontolinje / kontopost (på engelsk "account", men et egentlig regnskabsbegreb), transaktion (gælder både indtægter og udgifter, men knyttet til regnskabsvæsen).

Det foreslås i stedet, at der etableres en tekstboks henover Tomme rækker og Kontoplaner, som netop kaldes Kontoplaner, for det er jo netop hvad disse dækker over. Der er tale om to kontoplaner, hvor den ene har data (levetider, enhedspriser mv.) og den anden ikke har data. De to kontoplaner kaldes således:
- Tomme rækker omdøbes til: Uden data (UK: No data)
- Kontoplaner omdøbes til: Med data (UK: Data included)

**Comment by Difference** [comment]
Dette issue går på nye navne til de tomme rækker, altså at "Anskaffelse" etc. , således at det ikke er gentagelser af rækkenavn og omkostningstype.

Eks: Forvalting ny række:

![image](https://user-images.githubusercontent.com/142553/69032723-76932a80-09dd-11ea-998b-01826f9b81e8.png)


Bygningsdele har ikke problemet, men alle andre rækker skal have nye navne, både på dansk og engelsk.

![image](https://user-images.githubusercontent.com/142553/69032574-23b97300-09dd-11ea-90a8-13804b4c40ad.png)

**Comment by Difference** [comment]
Den engelske skabelon løser det nogle steder ved at tilføje "costs" så det er måske en mulighed:

![image](https://user-images.githubusercontent.com/142553/69033053-5b74ea80-09de-11ea-9200-f3c6780e8b9a.png)


Der skal altså findes enkle synonymer/erstatninger for: ( på dansk )
Ansaffelse
Engangsudgift
Forvalting
Renhold
Løbende indtægt
Engangs indtægt

**Comment by elcycefil** [comment]
Rækkenavne:
Anskaffelse som rækkenavn erstattes af Grundkøb: Land acquisition costs
Éngangsudgifter: One-off costs
Bygningsdel/inventar/udstyr: Building component costs
Forvaltningsudgifter: Management costs
Forsyningsudgifter: Utility costs
Renholdsudgifter: Cleaning costs
Indtægter – løbende: Income – recurring 
Indtægter – engangs: Income – one-off 

Typenavne (ændres også på engelsk i ”de blå felter” og rapporter fra acquire, restore mv.):
Anskaffelse: Acquisition
Engangsudgift: Non-recurring costs
Vedligehold: Maintenance
Genopretning: Replacement
Forsyning: Supply
Renhold: Cleaning
Løbende indtægt: Recurring income
Engangsindtægt: Non-recurring income

Bemærk: Indtægt skal ændres til ”Løbende indtægt”.

**Comment by Difference** [comment]
Grundkøb er nok for specifikt, da der findes andre anskaffelser der har restværdi.
Ligeledes er Bygningsdel/inventar/udstyr ikke generisk nok.

Ideelt set bør navnene være generiske og selvforklarende, altså begreber der dækker:

“Anskaffelser med blivende værdi/restværdi og evt. afskrivning, men uden drift og genopretning.”
“Anskaffelser med drift, genopretning og restværdi”

**Comment by Difference** [comment]
Måske bør Anskaffelser udgå bygningsdele omdøbes?

"Bygningsdel/udstyr/anskaffelse" eller lignende.

**Comment by Difference** [comment]
"manage" mangler på listen, er nu oversat til "Management"

**Comment by elcycefil** [comment]
"Management" skal naturligvis med.

**Comment by elcycefil** [comment]
Mere generiske navne bliver meget lange navne, men er omvendt mere beskrivende.

Navne:
-	Anskaffelse – uden drift, genopretning og restværdi
-	Anskaffelse – med restværdi, men uden drift og genopretning
-	Anskaffelse – med drift, genopretning og restværdi
Navne på engelsk: 
-	Acquisition – without maintenance, replacement and residual value
-	Acquisition – with residual value, but without maintenance and replacement
-	Acquisition – with maintenance, replacement and residual value

**Comment by Difference** [comment]
Egentlige beskrivelser kan lægges i "Description" der allerede bliver vist som Tooltip, mår musen holdes over en række. 

![image](https://user-images.githubusercontent.com/142553/69224736-5ef2a800-0b7d-11ea-82ea-7187965b815b.png)


De navne der vælges lever videre i eksport og som det "grønne" navn, så de bør være helt enkle.

**Comment by elcycefil** [comment]
Implementeret.
