### ISSUE TITLE
"Rapporter" - angiv procenter (procentvisning) i "Beregningsforudsætninger"

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#354]

**Comment by Difference** [comment]
Uddyb venligst, der er % tegn på forudsætninger.

![image](https://user-images.githubusercontent.com/142553/68684808-61477780-0569-11ea-8740-27169c62e29c.png)

**Comment by HAW19** [comment]
Jens' kommentar var rettet mod "Rapport" sektionen, hvor værdier vises i tabelform.

![image](https://user-images.githubusercontent.com/55234063/68842693-19d6fd80-06c7-11ea-85c3-cf59e84c70dd.png)

**Comment by Difference** [comment]
Tak! Fixed.
