### ISSUE TITLE
"Rapporter" - det er ikke nødvendigt at vise "Restværdi" for hvert år i "Omkostninger i beregningsperioden". Det er kun relevant at vise en "Restværdi" for slut året for beregningsperioden. 

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#360]
Overvej om den årlige "Restværdi" kan vises i en separat tabel.

**Comment by Difference** [comment]
Restværdier fjernet og rapportafsnittet omdøbt til "Pengestrømme i beregningsperioden"

Valget medfører at det ikke længere er muligt at kontrollere at afskrivning sker korrekt.
