### ISSUE TITLE
'Inddatering': Det vil være rart, hvis brugeren kunne se summen af inddaterede værdier.

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#364]
![image](https://user-images.githubusercontent.com/55234063/68591009-0f7eee80-0490-11ea-9372-a548fbc4f4a5.png)

**Comment by Difference** [comment]
Prøv at beskrive en usecase, hvor det giver added value til brugeren, fremfor at se i  de  blå felter.

Summen vil jo være en blanding af forskellige omkostingstyper, f,eks. forsyning, anskaffelse, renhold mv.

Det synes ikke at give mening at summe disse sammen.

**Comment by HAW19** [comment]
Jeg sad med en af vores kollegaer, Thomas, der gerne vil lave en totaløkonomisk beregning ifm. et projekt. Hans umiddelbar reaktion var, at han ikke kunne se summen af alle hans indtastninger. Han ville gerne se et samlet beløb for hver gruppe (fx Terræn og bygning).

**Comment by Difference** [comment]
Prøv at beskrive hvordan det giver mening på tværs af rækketyper.

![image](https://user-images.githubusercontent.com/142553/68594526-072ab180-0498-11ea-9f2a-7a9cd6e91820.png)

**Comment by HAW19** [comment]
Du har ret i, at det ikke giver mening på tværs af de forskellige omkostningstyper. 
Kan det tænkes, at der angives opsummerede værdier for både udgifter og indtægter (dvs. samlede udgifter/indtægter)?

**Comment by Difference** [comment]
1) Vi skal prøve at forstå hvorfor han gerne vil se summen, for at evt. at imødekomme ønsket.
2) Problematikken er at der bl.a. blandes anskaffelsesomkostninger punktvise omkostninger sammen, derfor er det kun opstillinger som i det blå resultatfelt der giver mening.  

En "Sum" kan f,eks. falde i i år 4, en anskaffelse i år 7 og vedligehold punktvis over denne periode.


3) Det er vigtigt at forstå virkemåden, og jeg tænker du kan forklare Thomas denne?

**Comment by Difference** [comment]
Der kan måske tænkes en virkemåde, hvor de "blå resultater" , skifter til den gruppe der er åben/aktiv og hvis alle grupper er lukkede, vises den nuværende visning, altså summen på tværs af grupper.

**Comment by HAW19** [comment]
Det lyder meget fint. Jeg vil forklare ham grundprincipperne og den problemstilling som du påpeger. 

Ja, det kan være, at vi kan få opfyldt hans ønsker ved en aktiv gruppe, hvor han kan se summen på tværs af grupper. Den del skal jeg nok afklare med Thomas inden vi gå videre med det :)

**Comment by Difference** [comment]
Det lyder godt, men det adresserer ikke at dette issue, ikke har en årsag. "Det ville vare rart" må dække over et egentligt behov, altså f.eks. 

Hvad er foremålet med at få vist en sum, og hvilket problem løser det?
En sum af hvad og hvorfor?.

**Comment by Difference** [comment]
Lukkes
