### ISSUE TITLE
"Restværdi" påvirkes ikke af inddatering i "Vedligehold"

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#365]
![image](https://user-images.githubusercontent.com/55234063/68591235-84522880-0490-11ea-9b99-39b95c316fee.png)

![image](https://user-images.githubusercontent.com/55234063/68591296-af3c7c80-0490-11ea-92f0-c5638a795d72.png)

**Comment by Difference** [comment]
Vedlighold påvirker ikke restværdi, denne lukkes.
