### ISSUE TITLE
"Inddatering": Når der angives et "Interval" for vedligehold, ændres beløbet i "Vedligehold (kr/gang)" automatisk.

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#366]
![image](https://user-images.githubusercontent.com/55234063/68591559-46a1cf80-0491-11ea-99f5-3787d23cba32.png)

![image](https://user-images.githubusercontent.com/55234063/68591655-84065d00-0491-11ea-880a-319359064f95.png)

**Comment by Difference** [comment]
Ja. Det er korrekt virkemåde, er der et issue her?

**Comment by HAW19** [comment]
Jeg havde lukket den, men ved en fejl kom til at åbne den igen. Så den skal vi se bort fra.

**Comment by Difference** [comment]
Jeg lukker :-)
