### ISSUE TITLE
Skabeloner til almene boliger skal anvende rente- og prisudviklingssæt med fast rente

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#370]

**Comment by Difference** [comment]
Fast nominel eller Fast realrente?

![image](https://user-images.githubusercontent.com/142553/69044980-342a1780-09f6-11ea-9e33-4cfc02d58546.png)

**Comment by elcycefil** [comment]
Fast realrente.

**Comment by Difference** [comment]
Fixed
