### ISSUE TITLE
DGNB skabeloner

### ISSUE THREAD

**Issue by Difference** [Difference/LCCbygBase#374]
Bør  DGNB skabeloner have tommer grupper, med den fra DGNBs side ønskede inddeling?

Således kan der til DGNB hospitalsskabelon tilføjes grupper, med angivet levetidsinteval, der hjælper brugerne til den rigtige inddateringsmetodik.

![image](https://user-images.githubusercontent.com/142553/69139025-06110a00-0ac0-11ea-9803-0a486caec267.png)

**Comment by elcycefil** [comment]
Ja, det vil være en god ide at have to ekstra grupper for "Operationsstue" og "Sengestue". De bør være placeret lige efter Terræn og bygning.

I samme ombæring bør Inventar og udstyr slettes, da den ikke bruges i DGNB.

**Comment by Difference** [comment]
DGNB skabeloner er pt. tomme, så der skal indsættes grupper, når beta 7 er ude, hvor det er muligt at inddatere gruppe intervaller. @HAW19 Kan du tage denne når du får beta 7?

**Comment by HAW19** [comment]
Ja, det kan I tro. Jeg skal nok sørge for det

**Comment by HAW19** [comment]
Levetid på rækkeniveau kan ikke slettes. se figuren
![image](https://user-images.githubusercontent.com/55234063/70249970-76d14b00-177d-11ea-9270-d03637cfe0fe.png)

**Comment by Difference** [comment]
Kan ikke umiddelbart reproduceres i beta 07 : her er levetidsfeltet valgt, og der er trykket [<-] og [Enter]

![image](https://user-images.githubusercontent.com/142553/70252401-ab470600-1781-11ea-831d-89deb276665f.png)

**Comment by HAW19** [comment]
Når man sletter 15, så dukker der andet tal op (fx 80). Skal jeg lade det tal stå, eller blot skrive 0 i feltet?

**Comment by HAW19** [comment]
Ok, korrekt virkemåde

**Comment by elcycefil** [comment]
Fixed
