### ISSUE TITLE
"Forsyning" i kontoplaner inddeles i to: Udgifter og Indtægter + solceller konverteres til løbende indtægt i eksempelprojekt

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#381]

**Comment by Difference** [comment]
Kontrol af flytning, ser rigtig ud

![image](https://user-images.githubusercontent.com/142553/69821211-44ff3800-1203-11ea-8db2-326b545c73f2.png)

**Comment by Difference** [comment]
Dette skaber nye issues, se #382 og #383

**Comment by Difference** [comment]
Implementeret  i tomt standardprojekt i 648c2bca2918ccc42f31dc8aa56c0649d687da07
