### ISSUE TITLE
"Rapporter": Rapportafsnit i projekter, der er oprettet i version 3.0.06 eller ældre, bliver ikke vist i version 3.0.07. 

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#384]
Forklaring kan være, at posterne er grupperet anderledes i version 3.0.07. Se figuren:

![image](https://user-images.githubusercontent.com/55234063/69822840-9f9a9300-1207-11ea-85c6-b33ab3889983.png)

**Comment by Difference** [comment]
Før release af endelig version, kan der ikke på regnes versionskompabilitet. brug v 07 projekter i version 07. hvis der er behov for konvertering, kan der klippe klistres i xml.
