### ISSUE TITLE
Gemmefunktion Ctrl-s fungerer ikke

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#390]
I version 3.0.07 (Beta 7) opdateres gemte projektfiler ikke ved brug af Ctrl-s.

**Comment by Difference** [comment]
Kan ikke reproduceres, dog mangler der besked i infolinjen om at projektet gemmes.

Hvis kun infolinje mangel : Denne kan lukkes.
Hvis der rent faktisk ikke gemmes : Fremstil step by step, der kan reproducere fejlen.

**Comment by elcycefil** [comment]
Step-by-step:
- Åbning af eksisterende projektfil
- Rettelser i projektfil
- Ctrl-s for at gemme oven i eksisterende projektfil 
- Rettelser gemmes ikke
