### ISSUE TITLE
LCCbygBase - DGNB hospital eksempelprojekt: skal jeg tilføje de to nye grupper "Operationsstuer" og "Sengestuer" i Conformity check og Certificering? 

### ISSUE THREAD

**Issue by HAW19** [Difference/LCCbygBase#395]
![image](https://user-images.githubusercontent.com/55234063/70422812-a6799f00-1a6c-11ea-9de9-ce9f54954f38.png)

**Comment by Difference** [comment]
Ja, de skal også rettes til, med flytning af rækker og sletning af levetid i rækker.
