### ISSUE TITLE
Ctrl-s gemmer i systemmappe

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#397]
Med version 3.08 (RC1 temporary) gemmes projektfiler i systemmappen, hvis Ctrl-s anvendes.

**Comment by Difference** [comment]
Hvad og hvordan åbnes? 
“Åben Fil”, eller skabelon eller dobbeltklik på fil, der åbner LCCbyg?

**Comment by Difference** [comment]
Kan ikke umiddelbart reproduceres, kan der fremstilles en step by step?
