### ISSUE TITLE
Brug af ENTER for at sikre at data er korrekt registreret

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#47]
Det er usikkert hvornår indtastede ting bliver gemt, f.eks. kalkulationsperiode. Hvis man skriver 30 i kalkulationsperiode og går direkte op og gemmer så bliver der ikke gemt. Man skal trykke på ENTER først.

**Comment by elcycefil** [comment]
Tekst i felt gemmes kun hvis man trykker på Enter. Det er vi ikke vant til fra fx Excel.

**Comment by Difference** [comment]
kalkulationsperiode opdateres nu løbende
