### ISSUE TITLE
Beregningsforudsætninger - inkludere flere energiformer

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#49]
Der bør tilføjes prisudviklinger plus enhedspriser for flere forskellige energiformer.

**Comment by elcycefil** [comment]
Værdier i gule felter inkluderes i LCCbyg for henholdsvis Standardskabeloner og DGNB-skabeloner.
[Energipriser og stigningstakter.xlsx](https://github.com/Difference/LCCbygBase/files/580247/Energipriser.og.stigningstakter.xlsx)

**Comment by Difference** [comment]
rettes i ny version af dgnbkontor.xml
