### ISSUE TITLE
Indsæt ny række - placering

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#50]
Når man vælger at indsætte ny række i kontoplan, er det ikke helt klart, hvor den kommer frem. Umiddelbart ville det være godt, hvis den nye række kom øverst dvs. dér hvor man ca. klikker og kan se den.

**Comment by Difference** [comment]
Her er den valgte løsning
![image](https://cloud.githubusercontent.com/assets/142553/20211116/5154c91c-a7fd-11e6-852c-399937c6cad7.png)
