### ISSUE TITLE
Flytte rundt på rækkefølge af rækker

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#51]
Det ville være rart, hvis man kunne rykke rækker op og ned, netop fordi det f.eks. tilsyneladende ikke er muligt at sætte en række ind på førstepladsen.

Kolonner under Inddatering kan vilkårligt flyttes rundt, så rækkefølgen kan ændres. Noget tilsvarende ville være ønskeligt for rækker, undergrupper og hovedgrupper.

**Comment by Difference** [comment]
Jeg har designet en ny ikon, der vil tillade at indsætte, både over og under det valgte

![image](https://cloud.githubusercontent.com/assets/142553/20011125/ccf38142-a2aa-11e6-84bb-33adefd1cdcb.png)

**Comment by Difference** [comment]
Udgaver der indskriver hver del i et kvadrat
![image](https://cloud.githubusercontent.com/assets/142553/20011810/1cd76744-a2ad-11e6-9334-d99b3bb9e64c.png)

**Comment by Difference** [comment]
duplicate #50
