### ISSUE TITLE
Rapporttitel samt projekttype i titellinje

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#52]
Navnet på projektet kunne stå oppe i den øverste linje på skærmen, så man kan se hvilket projekt man er i når man har behov for at skifte mellem flere projekter.

**Comment by Difference** [comment]
duplicate #21

**Comment by Difference** [comment]
Navnet kan fremgå i titellinien formen <rapportnavn><projekttypenavn><lccbygversion>
Omvendingen vil bringe rapportnavnet i fokus og give overblik, når flere LCCbyg kopier er åbne samtidigt.
For at skabeloner fremtræder logisk på statrskærmen, skal rapporttitel og projekttypenavn ikke bindes sammen.
