### ISSUE TITLE
Markering af tekst i felter

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#54]
Det ville være godt at man kunne markere hele teksten i felterne med et klik i feltet. Det kan man ikke i alle felterne. Her er set på Antagelser.

**Comment by Difference** [comment]
Dette gælder bl.a i navngivning af grupper.

![image](https://cloud.githubusercontent.com/assets/142553/20211906/f06b8416-a800-11e6-8c78-6d5fdb126f19.png)
