### ISSUE TITLE
Advarsel ved afslut/gem +evt. autogem

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#55]
Meddelelsen på print screen nedenfor er svær at forholde sig til.  Første gang man ser den bør den sige direkte at man skal gemme før man lukker. Når den kommer op igen, når man så lukker efter man har gemt, bør dette fremgå.
![afslut](https://cloud.githubusercontent.com/assets/18067512/19928117/5ec83f4a-a0fd-11e6-9387-52391c9914b8.jpg)

**Comment by Difference** [comment]
Flere brugere foreslår at autogemmer, ligesom det kendes fra nyere versioner af word/excel.
En bruger foreslår at Promt ved afslutning ændres, til "Du har foretaget ændringer siden du gemte sidst, vil du gemme nu?" eller lign, altså en omvending af   "ja/nej"
