### ISSUE TITLE
De blå felter i venstre kolonne er svære at forstå (Inddatering/Resultater fra denne kontoplan)

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#56]
Det bør overvejes at fjerne venstre kolonne af blå felter - det er tilsyneladende svært at forstå og skaber mere forvirring end afklaring. Som minimum skal vejledning forbedres.

**Comment by Difference** [comment]
Venstre kolonne kan måske flyttes til "kontoplaner"?
Det er jo vigtigt at man kan se kontoplanens beregningsmetode og hvor LCCbyg posterer kontoplanens resultater

**Comment by Difference** [comment]
Løst på følgende måde, under kontoplaner:
![image](https://cloud.githubusercontent.com/assets/142553/20265078/3eb6a23e-aa6f-11e6-86ec-b9659975221d.png)

Under Inddatering: 
![image](https://cloud.githubusercontent.com/assets/142553/20265088/58f8495e-aa6f-11e6-9b81-536f0b8585dc.png)
