### ISSUE TITLE
Låst/åben skabelon

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#61]
Det bør være muligt at have nogle dele af fx en standardskabelon låst op (fx renhold), mens den tilsvarende del er låst i DGNB-skabeloner.

**Comment by Difference** [comment]
Det er muligt at låse en kontoplan i en projekttype (f.eks. DGNB) , uden at den er låst i en anden projekttype, da der jo er tale om forskellige projektskabeloner.

Det er også muligt at have en kontopaln med både låse og ulåste dele.
