### ISSUE TITLE
Forsyning - enheder mangler

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#63]
Enheder (m3, kWh, MWh) mangler på Forsyning i alle skabelonernes Kontoplaner.
![forsyning-udklip](https://cloud.githubusercontent.com/assets/18067512/20142466/22dca56e-a695-11e6-903d-b01929706bf8.PNG)

**Comment by elcycefil** [comment]
Alle energienheder skal være i kWh (ikke MWh).

**Comment by Difference** [comment]
Hvilke af disse enheder skal evt ændres i For og hoveprojekt: 
![image](https://cloud.githubusercontent.com/assets/142553/20172280/bca7cc88-a734-11e6-815d-2279ad39de37.png)

Hvilke af disse enheder skal evt ændres i DGNB Kontor:
![image](https://cloud.githubusercontent.com/assets/142553/20172567/eb046d38-a735-11e6-9961-a4adb5304211.png)

**Comment by Difference** [comment]
Seneste DGNBkontor fil har de nye emheder og værdier inddateret
