### ISSUE TITLE
Korrekturrettelse: Indlæsning af projektfil fra tidligere version

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#64]
Ved indlæsning af projektfil fra tidligere version af værktøjet får brugeren en advarselsmeddelelse. Teksten heri rettes til nedenstående:

Det indlæste projekt er udarbejdet i en tidligere udgave af LCCbyg.
Du har muligvis ikke fået indlæst alle informationer og visninger. Du kan fortsætte med at arbejde, men du bør tjekke, at dine inddateringer er korrekte.
Du bør være opmærksom på, at LCCbyg fra version 2.1.0 ikke længere benytter et automatisk arvesystem mellem alternativer.
Din programversion er: LCCbyg 2.1.6.
Det indlæste projekt er udarbejdet i LCCbyg 2.1.2.

**Comment by Difference** [comment]
Teksten ændret til: 

Det indlæste projekt er udarbejdet i en tidligere udgave af LCCbyg.

Du har muligvis ikke fået indlæst alle informationer og visninger. Du kan fortsætte med at arbejde, men du bør **kontrollere**, at dine inddateringer er korrekte.
Du bør være opmærksom på, at LCCbyg fra version 2.1.0 ikke længere benytter et automatisk arvesystem mellem alternativer.

Din programversion er: {0}

Det indlæste projekt er fremstillet i {1}
