### ISSUE TITLE
Handlinger - > "Vælg projekt til sammenligning"

### ISSUE THREAD

**Issue by Difference** [Difference/LCCbygBase#66]
Der mangler hjælpetekst til "Handlinger - > Vælg projekt til sammenligning"

Det skal bl.a forklares, hvilke felter der markeres med grønt, og hvilke der kan/ikke kan forventes markeret.
Der bør også skitseres en "usecase", altså at funktionen kan bruges til at kontrollere at der ikke er ændret i basedata.

**Comment by elcycefil** [comment]
Hjælpetekst er opdateret.
