### ISSUE TITLE
Mængde nulstilles ikke ved sletning under Inddatering i standardskabeloner

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#70]
Når værdier for mængder slettes under Inddatering i standardskabelonen For- og hovedprojekt, bliver mængden automatisk sat til værdien "1" og ikke til værdien "0", som den bør. Værdien kan kun sættes til "0", hvis man aktivt skriver "0" i feltet. 
Tjekkes også i de øvrige standardskabeloner.

**Comment by Difference** [comment]
Denne opførsel er udført på baggrund af et tidligt følgegruppemødeønske. Det er muligvis på tide at ændre funktionaliteten så sletning ikke bliver erstattet af "1" mængde, men da nogle kontoplaner opererer med skjult mængde (som forudsættes at være 1), skal der en længere testperiode til at ændre denne opførsel. Ændringen gennemføres derfor ikke til milestone 2.1.7

**Comment by Difference** [comment]
Værdien bør vel retteligt sætte til "NULL", altså ingenting, hvis programmet skal opføre sig konsistent?
