### ISSUE TITLE
Genvejstast til "Luk projekt"

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#75]
Genvejstast til ”Luk projekt”, så man kommer tilbage til skabelonerne, vil være en stor hjælp.

I MS Office hedder genvejstasten Ctrl-F4.

**Comment by Difference** [comment]
Implementeret med Ctrl-F4. Ctrl+W er også evalueret, men valgt fra i først omgang. Kan evt. tilføjes som ekstra genvej senere.
