### ISSUE TITLE
Ændring af levetid - konsekvensrettelse af genopretningsomkostning (grønne tal)

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#77]
I skabelonen For- og Hovedprojekt under Inddatering anvendes grønne tal til at vise de beregnede vedligeholds- og genopretningsomkostninger. Hvis man ændrer i levetiden (et grønt tal) fx fra 120 år til 20 år, bliver Resultater fra denne kontoplan (de blå felter i toppen) korrekt ændret. Kolonnen med Genopretning (grønne tal) bliver dog ikke ændret til sorte tal ved en ændret levetid, men står uændret med grønt og den beregnede værdi på basis af baseværdien fra Kontoplaner. Dette princip bør nok overvejes ved en senere revision.

**Comment by Difference** [comment]
Prisen på genopretning er ikke afhænge af, ej heller bundet til levetid.
