### ISSUE TITLE
Forklaring til skabelongrupper

### ISSUE THREAD

**Issue by Difference** [Difference/LCCbygBase#85]
Der mangler dokumentation om skabelongrupper og deres virkemåde.

Stikord: 

Skabelongrupper er undergrupper der automatisk kopierer deres rækker.
De virker kun når kontoplanen er låst.
Når en kontoplan låses op, fjernes alle undergrupper, der er baseret på samme skabelongruppe, undtagen een.
Når kontoplanen er låst, kopieres skabelongruppen, når man indsætter en ny undergruppe over eller under den.
De tilføjede undergrupper (eller originalen) kan slettes, **undtagen den sidste kopi**, der herefter udgør skabelonen.

**Comment by elcycefil** [comment]
Brugervejledning er opdateret.
