### ISSUE TITLE
Forsyning: Alle enhedspriser i kWh

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#86]
Alle enhedspriser for 'Forsyning' i standardskabelonen 'For- og hovedprojekt' bør ligesom DGNB Kontorbyggeri opgøres kWh i stedet for ton, l, m3 og MWh.
 Forklaring/notetekster til vejledning/manual vedr. energi:
•Træpiller: Brændværdi 5 kWh/kg, virkningsgrad ca. 80 %, pris 1.600 kr/tons ekskl. moms = 0,40 kr/kWh
•Olie: Brændværdi 10 kWh/l, virkningsgrad 85 %, pris 9,47 kr/l ekskl. moms = 1,11 kr/kWh
•Gas: Brændværdi 11 kWh/m3, virkningsgrad 100 %, pris 7,14 kr/m3 ekskl. moms = 0,65 kr/kWh

**Comment by Difference** [comment]
Der skal afklares en ny eksempleinddatering for "Varme- Fjernvarme" pt 👍 
![image](https://user-images.githubusercontent.com/142553/29776423-ded176ec-8c08-11e7-9a8f-cc2c0a237220.png)

**Comment by elcycefil** [comment]
Eksempeldata opdateres for fjernvarme med enhedspris på 0,52 kr/kWh og mængde på 64.000 kWh, så eksempelprojektet er identisk med det tidligere eksempelprojekt.

**Comment by Difference** [comment]
Opdateret i ver. 2.2.20
