### ISSUE TITLE
For- og hovedprojekt/Kontoplaner/Rengøring - kolonnen 'Bemærkning' er aktiv, men skal slettes

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#93]

**Comment by Difference** [comment]
Kolonnen bruges til at notere detaljer, og er specielt nyttig når der inddateres årlige udgifter.

**Comment by elcycefil** [comment]
Det er den eneste kontoplan, hvor muligheden er til rådighed. Vi bør være konsekvente i vores brug af felter til kommentering. Kolonnen kan også være nyttig for de andre kontoplaner, så der bør nok snarere etableres tilsvarende mulighed for de øvrige kontoplaner.
