### ISSUE TITLE
For- og hovedprojekt/Kontoplaner/Terræn og bygning - terrænomkostninger skal tilføjes

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#94]

**Comment by Difference** [comment]
Angivelse af om der er tale om en ny ønsket hovedgruppe, undergruppe række eller andet samt evt. nøgletal savnes i issue beskrivelse.

**Comment by elcycefil** [comment]
Der er tale om SfB-undergrupperne 10, 20, 30, 40, 50 og 60 med tilhørende rækker. De er alle tilføjet i DGNB-skabelonen, men mangler at blive opdateret/komme med i For- og Hovedprojekt.
Navne mv. fremgår i øvrigt også af regnearket med den engelske oversættelse (se #96).
