### ISSUE TITLE
Sammenlign projekt - grøn farve mangler under Grund, rådgivning og bygherre

### ISSUE THREAD

**Issue by elcycefil** [Difference/LCCbygBase#95]
Når man anvender funktionen "Vælg projekt til sammenligning" skal ens værdier markeres med grønt under "Inddatering". Det sker dog ikke for kontoplanen "Grund, rådgivning og bygherre", men dog for de øvrige kontoplaner.

**Comment by Difference** [comment]
"Vælg projekt til sammenligning", sammenligner baseværdier, ikke inputværdier, så LCCbygs visning er korrekt. Der synes at være behov for en bedre dokumentation og evt. omdøbning af menupunktet.
